In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\IMDB Dataset - IMDB Dataset.csv")
df.head(3)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [4]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [5]:
#Lowercasing

df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [6]:
# If i want to convert all movie review into lowercase then

df['review'] = df['review'].str.lower()
     

df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [7]:
#Remove Html tags

import re #regular expression
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)
     

text= " Movie1  Actor - Aamir Khan  Click here to download"
     

remove_html_tags(text)

' Movie1  Actor - Aamir Khan  Click here to download'

In [8]:
#now we remove tags from IMBD datasets
df['review']=df['review'].apply(remove_html_tags)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [9]:
#Remove Url

# If i want to remove urls from text then

def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)
     

text2='For notebook click https://www.deture.com/delta/note1234acc'
     

print(remove_url(text2))
     
#'For notebook click '

df['review']=df['review'].apply(remove_url)

For notebook click

In [10]:
#Remove Punctuation

import string
string.punctuation
     
'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

exclude=string.punctuation
     

def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  return text

     

text3= 'string. with. Punctuation?'
     

remove_punc(text3)
     
#'string with Punctuation'

df['review']=df['review'].apply(remove_punc)
     

df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [11]:
#Chatword Treatment

chat_words ={'u2': 'you too', 'BBL':'Be Back Later','GAL':'Get A Life'}
chat_words
     
# {'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get A Life'}

def chat_conversation(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)
     

chat_conversation('BBL')

'Be Back Later'

In [12]:
# Spelling Correction

from textblob import TextBlob
     
incorrect_text = "ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner."

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

In [13]:
# #Removing Stopwords

# import nltk # natural language tool kit
# nltk.download('stopwords')
# from nltk.corpus import stopwords
 

# STOPWORDS = set(stopwords.words('english'))
# #STOPWORDS
# # manually work
# def remove_stopwords(text):
#   new_text =[]
#   for word in text.split():
#     if word in set(stopwords.words('english')):
#       new_text.append('')
#     else:
#       new_text.append(word)
#   x=new_text[:]
#   new_text.clear()
#   return " ".join(x)
  
# remove_stopwords('probably my all-time favorite movie , a story of selflessness,sacrifice and dedication')
     
# 'probably  all-time favorite movie ,  story  selflessness,sacrifice  dedication'